version: "2"
linters:
  default: standard
  enable:
    - gocritic
    - godoclint
    - ginkgolinter
    - modernize
  settings:
    gocritic:
      enabled-checks:
        - ruleguard
      settings:
        ruleguard:
          failOn: all
          rules: ./ruleguard/import.go
