/*
Package pretty provides opinionated pretty-printing of SSA graphs to aid in
understanding. It is intentionally not(!) an all-including-the-kitchen-sink
pretty-printer, but rather limited.

If you happen to know how SSA dumps generated by “GOSSAFUNC=Foo go build ...”
look like, then please notice that the SSA graphs we get from [ast] and their
helper functions use “t0”, “t1”, ... instead of “v0”, “v1”, ...

[ast]: https://pkg.go.dev/golang.org/x/tools/go/ssa
*/
package pretty
